[S3C-3567] Create Account -4
scality/vaultclient-java pull request #10
Opened 2021-03-05 09:54 UTC by saitharunthodupunuru

2021-03-05 09:54 UTC, bert-e commented
# Hello saitharunthodupunuru,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/vaultclient-java/bert-e/doc/user).





*Status report is not available.*

2021-03-05 09:54 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-03-05 10:41 UTC, naren-scality approved these changes

2021-03-05 11:16 UTC, anurag4DSB requested changes
I might have not noticed this before as I didn't mention it prior. But the commit messages need to be in the right format.
It's the same as the branching but a little different.

General format(in this case assuming project is S3C):
```sh
feature: S3C-XXXX-commit-message-for-logic
bugfix: S3C-XXXX-commit message-for-logic
improvement: S3C-XXXX-commit-message-for-logic
```
Also, the first line of the commit message should be no more than 55 characters(including `feature: S3C-XXXX` / `bugfix: S3C-XXXX` and so on) as GitHub shows only 55 characters of commit message and if it is more than 55, GitHub shortens it using `...`

After this first line, you can have more explanation. If you have more explanation, it will be automatically taken into the Summary section of your PR. There is no character limit 

Example of a good commit message without any explanation: https://github.com/scality/Vault/commit/a0b44fc70c4dc8c8a0b01c6be4cba07acb57e794

Example of a good commit message with explanation: https://github.com/scality/Vault/commit/0b47b761c15dec7973adb5af2b0ed259cf9ff352

(you can make the explanation as bullet points as well to be consicise)

For further details on contributing I would suggest going through https://github.com/scality/Guidelines/blob/development/8.1/CONTRIBUTING.md
if you have any suggestions on how to improve any guidelines, do not hesitate to start a discussion on the guidelines project.

2021-03-05 11:16 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @anurag4dsb

2021-03-10 22:53 UTC, saitharunthodupunuru commented
@anurag4DSB 
Updated the commit messages as suggested. Added description on GIT PR.

2021-03-11 01:57 UTC, ilkescality approved these changes

2021-03-11 09:31 UTC, anurag4DSB approved these changes

2021-03-11 09:31 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-03-11 16:49 UTC, saitharunthodupunuru commented
/approve

2021-03-11 16:49 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-03-11 16:49 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue S3C-3567.

Goodbye saitharunthodupunuru.

2021-03-11 16:49 UTC, merged