feature/VCLTJV-3 test release
scality/vaultclient-java pull request #24
Opened 2022-08-16 19:21 UTC by XinLiScality

2022-08-16 19:21 UTC, bert-e commented
# Hello xinliscality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://bert-e.scality.net/scality/vaultclient-java/doc/user).





*Status report is not available.*

2022-08-16 19:21 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue VCLTJV-5 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.0.0`


Please check the `Fix Version/s` of VCLTJV-5, or the target
branch of this pull request.

2022-08-17 13:45 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer

2022-08-17 17:00 UTC, tcarmet approved these changes

2022-08-18 08:47 UTC, anurag4DSB requested changes

2022-08-18 08:47 UTC, anurag4DSB commented on docs/release.md
> +3. Once the release workflow is complete successfully, proceed to Nexus Repository Manager to manually release the project.
We are doing this as currently OSIS and vaultlcient-java share the same namespace and to automate closing and releasesing all previous versions should be closed and released.
# worth mentioning this as a comment with potential future improvement mentioned in the comment.

2022-08-18 08:47 UTC, anurag4DSB commented on docs/release.md
> +    password: Artesca12345!
For credentials, they are stored in github secrets or can be obtained by emailing Object Squad <[object-squad@scality.com](mailto:object-squad@scality.com)>
I would not want creds to be published in an open source repo :)

2022-08-18 08:47 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer






The following reviewers are expecting changes from the author, or must review again:

* @anurag4dsb

2022-08-22 09:31 UTC, anurag4DSB approved these changes

2022-08-22 09:31 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer

2022-08-22 09:41 UTC, XinLiScality commented
/approve

2022-08-22 09:43 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue VCLTJV-5.

Goodbye xinliscality.

2022-08-22 09:43 UTC, merged